package com.sullivan.disc.repository;



import com.sullivan.disc.model.Contact;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;

/**
 * <h1>ContactRepository</h1>
 * @author Shawn Sullivan
 * CEN 3024C-31774
 * July 8, 2025
 * The ContactRepository allows the upper layers of the Spring REST API to interact with the Contact table of the DB
 * directly and provides several autogenerated SQL query methods
 * Note: Spring-managed repositories are temporarily unused due to project requirement for dynamic user DB config.
 * Kept in code for future use because I would like to expand on this project and/or use it as a learning tool
 * later.
 */
public interface ContactRepository extends JpaRepository<Contact, Integer> {

    /**
     *  This query method is used by the service layer to verify whether a contact already exists in the Contacts table
     *  or needs to be created
     * @param firstName parameter provided via a ContactDTO sent from the frontend
     * @param lastName last_name value provided via a ContactDTO sent from the frontend
     * @param phoneNumber contact phone_number provided via a ContactDTO sent from the frontend
     * @return
     */
    //Optional<Contact> findByFirstNameAndLastNameAndPhoneNumber(String firstName, String  lastName, String phoneNumber);
}
