package com.sullivan.disc.repository;



import com.sullivan.disc.model.Disc;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

/**
 * <h1>DiscRepository</h1>
 * @author Shawn Sullivan
 * CEN 3024C-31774
 * July 8, 2025
 * The DiscRepository allows the upper layers of the Spring REST API to interact with the Discs table of the DB
 * directly and provides several autogenerated SQL query methods
 * Note: Spring-managed repositories are temporarily unused due to project requirement for dynamic user DB config.
 * Kept in code for future use because I would like to expand on this project and/or use it as a learning tool
 * later.
 */
public interface DiscRepository extends JpaRepository<Disc, Integer> {

//    List<Disc> findByContact_LastName(String contactLastName);
//
//    List<Disc> findByContact_PhoneNumber(String contactPhoneNumber);
//
//    List<Disc> findByReturnedTrue();
//
//    List<Disc> findBySoldTrue();
}
