package com.sullivan.disc.repository;



import com.sullivan.disc.model.Manufacturer;
import com.sullivan.disc.model.Mold;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;

/**
 * <h1>MoldRepository</h1>
 * @author Shawn Sullivan
 * CEN 3024C-31774
 * July 8, 2025
 * The MoldRepository allows the upper layers of the Spring REST API to interact with the Molds table of the DB
 * directly and provides several autogenerated SQL query methods
 * Note: Spring-managed repositories are temporarily unused due to project requirement for dynamic user DB config.
 * Kept in code for future use because I would like to expand on this project and/or use it as a learning tool
 * later.
 */
public interface MoldRepository extends JpaRepository<Mold, Integer> {

//    Optional<Mold> findByMoldAndManufacturer(String mold, Manufacturer manufacturer);
}
